### ISSUE TITLE
Am I missing "get organization networks"?

### ISSUE THREAD

**Issue by obrigg** [jbogarin/meraki-ansible-test#1]
Hi,
I thought leveraging GitHub issues will be an effective way to discuss and track feedback about the collection.
Trying to create a playbook that will iterate through several networks, I wanted to list the network of an organization (https://developer.cisco.com/meraki/api-v1/#!list-the-networks-that-the-user-has-privileges-on-in-an-organization). Looking into `networks.py` I can see how to create, delete, and update a network. However, I don't see how can I list the networks of the org.

Am I reading it wrong?

**Comment by obrigg** [comment]
Same for "get organizations" (https://developer.cisco.com/meraki/api-v1/#!list-the-organizations-that-the-user-has-privileges-on)

**Comment by obrigg** [comment]
I have found a pattern when it seems GET operations have a separate task (e.g. `networks_info.py` and `organizations_info.py`.
Does Ansible require GET methods to be separate modules?

With that, `organization info` is working fine. However, `networks_info` is failing with the following error:
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'DashboardAPI' object has no attribute 'organizationsnetworks'
[WARNING]: Failure using method (v2_runner_on_failed) in callback plugin
(<ansible.plugins.callback.default.CallbackModule object at 0x1029c58a0>): Object of type
AttributeError is not JSON serializable
```

**Comment by obrigg** [comment]
Found the reason.
`networks_info.py` lines 128 and 137 had `organizationsnetworks` as the family. Changing it to `organizations` fixed the problem. Creating a PR in a minute.

@fmunozmiranda, if this was auto-generated, can you kindly check why so that we won't have the same problem the next time we generate the collection off the OpenAPI spec?

**Comment by fmunozmiranda** [comment]
Thanks @obrigg, closing this due issue is fixed
