### ISSUE TITLE
worker found in a dead state

### ISSUE THREAD

**Issue by craigers521** [jbogarin/meraki-ansible-test#9]
#### Behavior:

when using the networks_wireless_ssids module to loop through a list of ssids to configure the playbook crashes with the following error: 

```
TASK [Configure ssids] ***********************************************************************************************************
Tuesday 11 July 2023  18:34:06 -0500 (0:00:00.098)       0:00:00.098 **********
objc[61686]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[61686]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
ERROR! A worker was found in a dead state
```

#### Workaround
i found that if i export no_proxy="*" to my environment then the playbook executes without fail, i'm not sure why this works.  I also tried limiting my forks to 1, that didnt resolve the issue though. 

#### Environment:  
playbook and inventory setup can be found here:  
https://gitlab.com/craigerstix/ansible_meraki_beta/-/blob/main/config_ssids.yml

MacOS Ventura 13.4
ansible-core==2.15.1
meraki==1.34.0
Python 3.11.4

ansible.utils                 2.10.3
cisco.meraki                  1.0.0

#### Expected behavior:  
should be able to execute playbook without having to configure no_proxy env

**Comment by craigers521** [comment]
found a blog post about the dead worker issue and no_proxy fix... idk if this is issue is core to ansible/mac or something about the module implementation that can be addressed... but i've been using ansible on my mac for years and i've never ran into this issue before: 

https://www.whatan00b.com/posts/debugging-a-segfault-from-ansible/

**Comment by fmunozmiranda** [comment]
As you can see in documentation, to solve this you have to do this:

## Attention macOS users

If you're using macOS you may receive this error when running your playbook:

```
objc[34120]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[34120]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
ERROR! A worker was found in a dead state
```

If that's the case try setting this environment variable:
```
export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
```
